### ISSUE TITLE
run script, failed?

### ISSUE THREAD

**Issue by TahiriNadia** [AviranLab/patteRNA#2]
```
nadias-mbp:patteRNA-latest nadia_tahiri$ patteRNA sample_data/weeks_set.shape dummy_test -vl --motif ".{5}" -f sample_data/weeks_set.fa
Some output files already exist. Overwrite them? [yes/no] yes
INFO - Using 4 parallel processes
INFO - Target motif  ->           .{5}
INFO - Loading input data         
INFO - Loading input data         ... done in 00:00:00
INFO - Building the training set  
/usr/local/lib/python3.7/site-packages/patteRNA-latest-py3.7.egg/patteRNA/rnalib.py:132: VisibleDeprecationWarning: Passing `normed=True` on non-uniform bins has always been broken, and computes neither the probability density function nor the probability mass function. The result is only correct if the bins are uniform, when density=True will produce the same result anyway. The argument will be removed in a future version of numpy.
  bins="auto", normed=True)
INFO - Building the training set  ... done in 00:00:00
INFO - Training set summary - 
       Initial transcripts        21
       Passed QC                  21
       Used transcripts           21
       # Data points (in GMM)     9771
       KL div                     0
INFO - Training with K=1 - iter #0 : logL nan
INFO - Training with K=1 - iter #1 : logL -2.005e+04
INFO - Training with K=1 - iter #2 : logL -1.97e+04
INFO - Training with K=1 - iter #3 : logL -1.921e+04
INFO - Training with K=1 - iter #4 : logL -1.9e+04
INFO - Training with K=1 - iter #5 : logL -1.894e+04
INFO - Training with K=1 - iter #6 : logL -1.892e+04
INFO - Training with K=1 - iter #7 : logL -1.891e+04
INFO - Training with K=1 - iter #8 : logL -1.89e+04
INFO - Training with K=1 - iter #9 : logL -1.89e+04
INFO - Training with K=1 - iter #10 : logL -1.89e+04
INFO - Training with K=2 - iter #0 : logL nan
INFO - Training with K=2 - iter #1 : logL -2.015e+04
INFO - Training with K=2 - iter #2 : logL -1.96e+04
INFO - Training with K=2 - iter #3 : logL -1.911e+04
INFO - Training with K=2 - iter #4 : logL -1.888e+04
INFO - Training with K=2 - iter #5 : logL -1.878e+04
INFO - Training with K=2 - iter #6 : logL -1.873e+04
INFO - Training with K=2 - iter #7 : logL -1.871e+04
INFO - Training with K=2 - iter #8 : logL -1.869e+04
INFO - Training with K=2 - iter #9 : logL -1.868e+04
INFO - Training with K=2 - iter #10 : logL -1.868e+04
INFO - Training with K=2 - iter #11 : logL -1.867e+04
INFO - Training with K=2 - iter #12 : logL -1.867e+04
INFO - Training with K=2 - iter #13 : logL -1.867e+04
INFO - Training with K=3 - iter #0 : logL nan
INFO - Training with K=3 - iter #1 : logL -2.022e+04
INFO - Training with K=3 - iter #2 : logL -1.956e+04
INFO - Training with K=3 - iter #3 : logL -1.907e+04
INFO - Training with K=3 - iter #4 : logL -1.883e+04
INFO - Training with K=3 - iter #5 : logL -1.874e+04
INFO - Training with K=3 - iter #6 : logL -1.87e+04
INFO - Training with K=3 - iter #7 : logL -1.868e+04
INFO - Training with K=3 - iter #8 : logL -1.867e+04
INFO - Training with K=3 - iter #9 : logL -1.867e+04
INFO - Training with K=3 - iter #10 : logL -1.866e+04
INFO - Training with K=3 - iter #11 : logL -1.866e+04
INFO - Training with K=3 - iter #12 : logL -1.866e+04
INFO - Training with K=3 - iter #13 : logL -1.865e+04
Traceback (most recent call last):
  File "/usr/local/bin/patteRNA", line 11, in <module>
    load_entry_point('patteRNA===latest', 'console_scripts', 'patteRNA')()
  File "/usr/local/lib/python3.7/site-packages/patteRNA-latest-py3.7.egg/patteRNA/cli.py", line 272, in main
    fp_logl=os.path.join(args.output, GLOBALS["output_name"]["logL_plot"]))
  File "/usr/local/lib/python3.7/site-packages/patteRNA-latest-py3.7.egg/patteRNA/gmmhmm.py", line 608, in take_snapshot
    curr_plt.render_to_png(fp_fit)
  File "/usr/local/lib/python3.7/site-packages/pygal-2.4.0-py3.7.egg/pygal/graph/public.py", line 118, in render_to_png
    import cairosvg
  File "/usr/local/lib/python3.7/site-packages/CairoSVG-2.3.0-py3.7.egg/cairosvg/__init__.py", line 42, in <module>
    from . import surface  # noqa
  File "/usr/local/lib/python3.7/site-packages/CairoSVG-2.3.0-py3.7.egg/cairosvg/surface.py", line 25, in <module>
    import cairocffi as cairo
  File "/usr/local/lib/python3.7/site-packages/cairocffi-1.0.2-py3.7.egg/cairocffi/__init__.py", line 39, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2', 'cairo.so.2')
  File "/usr/local/lib/python3.7/site-packages/cairocffi-1.0.2-py3.7.egg/cairocffi/__init__.py", line 36, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2 / cairo.so.2
```

**Comment by MirkoLedda** [comment]
Hi Nadia. Seems that the `cairo` package is missing. If you have homebrew installed, then simply run `brew install cairo`. Else, run `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` and then the brew command. Let me know if that worked. I planned on removing the dependence on Cairo and use Matplotlib instead for future releases.

**Comment by TahiriNadia** [comment]
Hi @MirkoLedda,
Thank you for your fast answers. Effectively, it will be very interesting to use `Matplotlib`.
I used your indication by `brew install cairo` and it's works 👍
